StudentCatalog/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace StudentCatalog.Models
{
    public class Student
    {
        //C#: Properties start with capital letter

        //Java way of doing things..
        //private int studentId;

        //public void setStudentId(int studentId)
        //{
        //    this.studentId = studentId;
        //}

        //public int getStudentId()
        //{
        //    return studentId;
        //}

        public int StudentId {get ; set; }

        [Required(ErrorMessage = "Firstname is required")]
        public String Firstname { get; set; }
        
        [Required(ErrorMessage = "Lastname is required")]
        public String Lastname { get; set; }
        
        [Required(ErrorMessage = "Stupid you!")]
        [EmailAddress]
        public String Email { get; set; }

        public String MobilePhone { get; set; }

        public String ProfileImagePath { get; set; }

        public void SaveImage(
            HttpPostedFileBase image, 
            String serverPath, 
            String pathToFile)
        {
            if (image == null) return;

            string createFileWithName =
                Guid.NewGuid().ToString();

            ImageModel.ResizeAndSave(serverPath + pathToFile,
                createFileWithName, image.InputStream, 200);

            ProfileImagePath = pathToFile + createFileWithName + ".jpg";
        }
    }
}

StudentCatalog/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net.Mime;
using System.Web;
using System.Web.Mvc;
using StudentCatalog.Abstract;
using StudentCatalog.Models;
using StudentCatalog.Repositories;
using StudentCatalog.ViewModels;

namespace StudentCatalog.Controllers
{
    public class StudentsController : Controller
    {
        private IStudentRepository _studentRepository;
        private readonly ICompetencyHeaderRepository _competencyHeaderRepository;

        public StudentsController(IStudentRepository studentRepository, ICompetencyHeaderRepository competencyHeaderRepository)
        {
            _studentRepository = studentRepository;
            _competencyHeaderRepository = competencyHeaderRepository;
        }


        public string WannaPlayDad()
        {
            return "NO!";
        }

        // GET: Students
        public ActionResult Index()
        {
            ViewBag.Lucas = "Hi dad";
            List<Student> students = _studentRepository.GetAll().ToList();
            List<CompetencyHeader> competencyHeaders =
                _competencyHeaderRepository.AllIncluding(x => x.Competencies).ToList();

            StudentIndexViewModel vm = new StudentIndexViewModel
            {
                CompetencyHeaders = competencyHeaders,
                Students = students
            };

            return View(vm);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Student student = _studentRepository.Find(id);
            return View(student);
        }

        [HttpPost]
        public ActionResult Edit(Student student, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                string path = Server == null ? "" : Server.MapPath("~");
                student.SaveImage(image, path , "/UserUploads/ProfileImages/");
                _studentRepository.InsertOrUpdate(student);
                _studentRepository.Save();
                return RedirectToAction("Index");
            }
            return View(student);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Student());
        }

        [HttpPost]
        public ActionResult Create(Student student, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                //save
                string path = Server == null ? "" : Server.MapPath("~");
                student.SaveImage(image, path, "/UserUploads/ProfileImages/");
                _studentRepository.InsertOrUpdate(student);
                _studentRepository.Save();

                return RedirectToAction("Index");
            }
            else
            {
                return View(student);
            }   
        }
    }
}

StudentCatalog/Views/Students/Create.cshtml
@model StudentCatalog.Models.Student

@{
    ViewBag.Title = "Create";

//    @:  echo "like".
}

<h2>Create</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.Partial("_CreateEdit")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StudentCatalog/Views/Students/Edit.cshtml
@model StudentCatalog.Models.Student

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm(null, null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudentId)

        @Html.Partial("_CreateEdit")

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StudentCatalog/Views/Students/Index.cshtml
@using StudentCatalog.Models
@model StudentCatalog.ViewModels.StudentIndexViewModel

@{
    ViewBag.Title = "Index";
}



<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<div class="row">
    <div class="col-sm-3 hidden-xs" id="sidebar">
        <img src="~/Content/logo.png" class=" img-responsive " alt="Logo" />
    </div>


    <div class="col-sm-9">
        <div class="panel panel-default">
            <div class="panel-heading">
                Filter displayed students
            </div>
            
            
            <input id="filterBtn" type="button" value="Filter on competencies" 
                   class="btn btn-default"/>
            
            <input id="editCompetency" type="button" value="Edit competencies"
                   class="btn btn-primary" />
            
            <input id="newCompetencyHeader" value="Create competency header" type="button"
                   class="btn btn-danger"/>

            <div id="competecyHeadersDiv" class="MarginLeft40 Invisible">
                
                <div id="appendDiv" class="row ">
                   
                </div>

                @foreach (var compHeader in Model.CompetencyHeaders)
                {
                    <div class="FilterCompetencies">
                        <label class="lblHeader">
                            <input type="checkbox" name="competencyHeader" class="CompetencyHeader MarginRight5" />
                            @compHeader.Name
                        </label>
                        <span class="glyphicon glyphicon-plus Invisible"></span>

                        <div class="outerContainer">
                            @foreach (var competency in @compHeader.Competencies)
                            {
                                <div class="MarginLeft40 CompetencyDiv">

                                    <label class="CompetencyLabel">
                                        <input class="MarginRight5 Competency" type="checkbox" 
                                               name="Competencies" value="@competency.Name" />@competency.Name
                                    </label>
                                    <span class="glyphicon glyphicon-pencil Invisible"></span>
                                    <span class="glyphicon glyphicon-remove Invisible"></span>
                                </div>
                            }
                        </div>
                    </div>
                }
            </div>
        </div>



        <div class="row">
            @foreach (Student student in Model.Students)
            {
                <div class="col-lg-2 col-sm-3 col-xs-4">
                    <a href="@Url.Action("Edit", "Students", new { id=@student.StudentId})">

                        <img src="../../@student.ProfileImagePath" class="profileImage thumbnail img-responsive">
                    </a>
                </div>
            }
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<script type="text/javascript">
    $(function() {
        $("#filterBtn").click(function() {
            $("#competecyHeadersDiv").toggle('slow');
        });
        $("#editCompetency").click(function() {
            $(".glyphicon-plus, .glyphicon-pencil, .glyphicon-remove").toggle();
        });
        $(".glyphicon-plus").click(function() {
            $(this).parent().children(".outerContainer").append('<input type="text" class="form-control col-xs-8" ' +
                'placeholder="New Competency " /><div class="FloppyDiskDiv">' +
                '<span class="glyphicon glyphicon-floppy-disk"> </span></div>');
        });

        $(document).on("click", ".glyphicon-floppy-disk", function() {

            var data = { Name: "New value", CompHeader: "Design" };

            console.log($(this).parent().parent());

            //1: Get the value from the input text field
            //-  navigating with parent(), children(selector here)

            //2: Use the ajax call

            //3: In the success function: dynamically update the DOM (html) with the new 
            // competency.


            @*$.ajax({
                type: 'POST',
                url: "@Url.Action("Create", "Competencies")",
                data: JSON.stringify(data),
                dataType: 'json',
                contentType: "application/json; charset=utf-8",
                success: function (returnValue) {
                    alert(returnValue);
                },
                error: function () {
                    alert("failure");
                }
            });*@


        });

    });

</script>

StudentCatalog/Views/Students/Thanks.cshtml
@{
    ViewBag.Title = "Thanks";
}

<h2>Thanks</h2>

StudentCatalog/Views/Students/_CreateEdit.cshtml
@model StudentCatalog.Models.Student

<div class="form-group">
    @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.MobilePhone, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.MobilePhone, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.MobilePhone, "", new { @class = "text-danger" })
    </div>
</div>
<div>
    <img src="@Model.ProfileImagePath" alt="Profile image" title="Hi" />
    @Html.HiddenFor(x => x.ProfileImagePath)
</div>

<input type="file" name="image"/>

StudentCatalog/Views/Students/_StudentCreateEditView.cshtml
@model StudentCatalog.Models.Student

<label>Firstname</label>
<div>
    @Html.TextBoxFor(x => x.Firstname)
    @Html.ValidationMessageFor(x => x.Firstname)
</div>

<label>Lastname</label>
<div>
    @Html.TextBoxFor(x => x.Lastname, new { @class = "form-control" })
</div>

<label>Email</label>
<div>
    @Html.TextBoxFor(x => x.Email)
</div>

<label>Mobile Phone</label>
<div>
    @Html.TextBoxFor(x => x.MobilePhone)
</div>

<input type="submit" value="Save" class="btn btn-danger" id="myButton" />